// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukyzbjauydaqauknnxwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVreXpiamF1eWRhcWF1a25ueHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTE1ODYsImV4cCI6MjA2NDc2NzU4Nn0.bDvPDq0ajhHyGZm2NA5a1gy55Ez83ZHdGbttXVAyYrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);